<?php

namespace Database\Seeders;

use App\Models\Guest;
use Illuminate\Database\Seeder;

class GuestSeeder extends Seeder
{
    public function run(): void
    {
        $guests = [
            [
                'first_name' => 'Olusegun',
                'last_name' => 'Adebayo',
                'email' => 'olusegun.adebayo@email.com',
                'phone' => '+234-803-123-4567',
                'date_of_birth' => '1985-03-15',
                'nationality' => 'NG',
                'id_type' => 'national_id',
                'id_number' => 'NIN-12345678901',
                'company' => 'Dangote Industries',
                'job_title' => 'Group Executive Director',
                'vip_status' => 'diamond',
                'total_stays' => 52,
                'total_nights' => 156,
                'total_spent' => 85000000,
                'currency_code' => 'NGN',
                'preferred_language' => 'en',
                'preferred_currency' => 'NGN',
                'dietary_restrictions' => json_encode(['vegetarian']),
                'special_notes' => json_encode(['Prefers high floor', 'Late checkout requested']),
                'internal_notes' => 'VIP guest from Dangote Group, always ensure best room available.',
            ],
            [
                'first_name' => 'Ngozi',
                'last_name' => 'Okafor',
                'email' => 'ngozi.okafor@email.com',
                'phone' => '+234-806-234-5678',
                'date_of_birth' => '1990-07-22',
                'nationality' => 'NG',
                'id_type' => 'international_passport',
                'id_number' => 'A12345678',
                'company' => 'MTN Nigeria',
                'job_title' => 'Chief Technology Officer',
                'vip_status' => 'platinum',
                'total_stays' => 30,
                'total_nights' => 90,
                'total_spent' => 45000000,
                'currency_code' => 'NGN',
                'preferred_language' => 'en',
                'preferred_currency' => 'NGN',
                'dietary_restrictions' => json_encode([]),
                'special_notes' => json_encode(['Needs quiet room', 'Strong wifi required']),
                'internal_notes' => 'Frequent business traveler from MTN.',
            ],
            [
                'first_name' => 'Emeka',
                'last_name' => 'Nwankwo',
                'email' => 'emeka.nwankwo@email.com',
                'phone' => '+234-809-345-6789',
                'date_of_birth' => '1978-11-08',
                'nationality' => 'NG',
                'id_type' => 'international_passport',
                'id_number' => 'B23456789',
                'company' => 'Access Bank',
                'job_title' => 'Managing Director',
                'vip_status' => 'gold',
                'total_stays' => 18,
                'total_nights' => 54,
                'total_spent' => 28000000,
                'currency_code' => 'NGN',
                'preferred_language' => 'en',
                'preferred_currency' => 'NGN',
                'dietary_restrictions' => json_encode([]),
                'special_notes' => json_encode([]),
                'internal_notes' => 'Banking executive, prefers corporate billing.',
            ],
            [
                'first_name' => 'Fatima',
                'last_name' => 'Abubakar',
                'email' => 'fatima.abubakar@email.com',
                'phone' => '+234-812-456-7890',
                'date_of_birth' => '1992-01-30',
                'nationality' => 'NG',
                'id_type' => 'drivers_license',
                'id_number' => 'FKJ-1234567AA01',
                'company' => 'Nigerian National Petroleum Corporation',
                'job_title' => 'Senior Engineer',
                'vip_status' => 'silver',
                'total_stays' => 8,
                'total_nights' => 24,
                'total_spent' => 12000000,
                'currency_code' => 'NGN',
                'preferred_language' => 'en',
                'preferred_currency' => 'NGN',
                'dietary_restrictions' => json_encode([]),
                'special_notes' => json_encode(['Social media posts about stay']),
                'internal_notes' => 'NNPC guest, occasional conference traveler.',
            ],
            [
                'first_name' => 'Amina',
                'last_name' => 'Bello',
                'email' => 'amina.bello@email.com',
                'phone' => '+234-805-567-8901',
                'date_of_birth' => '1982-06-12',
                'nationality' => 'NG',
                'id_type' => 'international_passport',
                'id_number' => 'C34567890',
                'company' => 'GTBank',
                'job_title' => 'Executive Director',
                'vip_status' => 'diamond',
                'total_stays' => 60,
                'total_nights' => 180,
                'total_spent' => 95000000,
                'currency_code' => 'NGN',
                'preferred_language' => 'en',
                'preferred_currency' => 'NGN',
                'dietary_restrictions' => json_encode([]),
                'special_notes' => json_encode(['Treat with extra care', 'Preferred suite']),
                'internal_notes' => 'GTBank executive, frequent high-value guest.',
            ],
            [
                'first_name' => 'Chukwuemeka',
                'last_name' => 'Eze',
                'email' => 'chukwuemeka.eze@email.com',
                'phone' => '+234-808-678-9012',
                'date_of_birth' => '1988-09-05',
                'nationality' => 'NG',
                'id_type' => 'drivers_license',
                'id_number' => 'ENU-9876543BB02',
                'company' => 'Nigerian Breweries',
                'job_title' => 'Legal Counsel',
                'vip_status' => 'gold',
                'total_stays' => 15,
                'total_nights' => 45,
                'total_spent' => 18000000,
                'currency_code' => 'NGN',
                'preferred_language' => 'en',
                'preferred_currency' => 'NGN',
                'dietary_restrictions' => json_encode([]),
                'special_notes' => json_encode(['Early check-in when possible']),
                'internal_notes' => 'Legal professional, values consistency.',
            ],
            [
                'first_name' => 'Yetunde',
                'last_name' => 'Balogun',
                'email' => 'yetunde.balogun@email.com',
                'phone' => '+234-813-789-0123',
                'date_of_birth' => '1992-04-18',
                'nationality' => 'NG',
                'id_type' => 'international_passport',
                'id_number' => 'D45678901',
                'company' => 'Zenith Bank',
                'job_title' => 'Software Engineer',
                'vip_status' => 'silver',
                'total_stays' => 8,
                'total_nights' => 24,
                'total_spent' => 9500000,
                'currency_code' => 'NGN',
                'preferred_language' => 'en',
                'preferred_currency' => 'NGN',
                'dietary_restrictions' => json_encode(['vegetarian']),
                'special_notes' => json_encode(['Needs strong wifi']),
                'internal_notes' => 'Tech professional, values connectivity.',
            ],
            [
                'first_name' => 'Adaeze',
                'last_name' => 'Obi',
                'email' => 'adaeze.obi@email.com',
                'phone' => '+234-816-890-1234',
                'date_of_birth' => '1987-12-25',
                'nationality' => 'NG',
                'id_type' => 'international_passport',
                'id_number' => 'E56789012',
                'company' => 'Nestle Nigeria',
                'job_title' => 'Marketing Director',
                'vip_status' => 'platinum',
                'total_stays' => 25,
                'total_nights' => 75,
                'total_spent' => 35000000,
                'currency_code' => 'NGN',
                'preferred_language' => 'en',
                'preferred_currency' => 'NGN',
                'dietary_restrictions' => json_encode(['nut_allergy']),
                'special_notes' => json_encode(['Allergic to nuts - serious']),
                'internal_notes' => 'Nestle executive, frequent conference traveler.',
            ],
            [
                'first_name' => 'Tunde',
                'last_name' => 'Fashola',
                'email' => 'tunde.fashola@email.com',
                'phone' => '+234-817-901-2345',
                'date_of_birth' => '1980-08-14',
                'nationality' => 'NG',
                'id_type' => 'national_id',
                'id_number' => 'NIN-98765432109',
                'company' => 'Guinness Nigeria',
                'job_title' => 'VP Operations',
                'vip_status' => 'gold',
                'total_stays' => 12,
                'total_nights' => 36,
                'total_spent' => 22000000,
                'currency_code' => 'NGN',
                'preferred_language' => 'en',
                'preferred_currency' => 'NGN',
                'dietary_restrictions' => json_encode([]),
                'special_notes' => json_encode([]),
                'internal_notes' => 'Corporate account guest from Guinness.',
            ],
            [
                'first_name' => 'Grace',
                'last_name' => 'Okonkwo',
                'email' => 'grace.okonkwo@email.com',
                'phone' => '+234-811-012-3456',
                'date_of_birth' => '1993-02-28',
                'nationality' => 'NG',
                'id_type' => 'drivers_license',
                'id_number' => 'ABJ-5432109CC03',
                'company' => '',
                'job_title' => 'Yoga Instructor',
                'vip_status' => 'none',
                'total_stays' => 2,
                'total_nights' => 6,
                'total_spent' => 3500000,
                'currency_code' => 'NGN',
                'preferred_language' => 'en',
                'preferred_currency' => 'NGN',
                'dietary_restrictions' => json_encode(['vegan', 'gluten_free']),
                'special_notes' => json_encode(['Wellness retreat']),
                'internal_notes' => 'Wellness-focused guest.',
            ],
            [
                'first_name' => 'Aisha',
                'last_name' => 'Mohammed',
                'email' => 'aisha.mohammed@email.com',
                'phone' => '+234-802-111-2222',
                'date_of_birth' => '1975-10-03',
                'nationality' => 'NG',
                'id_type' => 'international_passport',
                'id_number' => 'F67890123',
                'company' => 'First Bank of Nigeria',
                'job_title' => 'Chairperson',
                'vip_status' => 'diamond',
                'total_stays' => 75,
                'total_nights' => 225,
                'total_spent' => 120000000,
                'currency_code' => 'NGN',
                'preferred_language' => 'en',
                'preferred_currency' => 'NGN',
                'dietary_restrictions' => json_encode([]),
                'special_notes' => json_encode(['Presidential suite always', 'Personal butler required']),
                'internal_notes' => 'Top VIP, chairperson of First Bank.',
            ],
            [
                'first_name' => 'Nnamdi',
                'last_name' => 'Azikiwe',
                'email' => 'nnamdi.azikiwe@email.com',
                'phone' => '+234-815-222-3333',
                'date_of_birth' => '1991-05-20',
                'nationality' => 'NG',
                'id_type' => 'international_passport',
                'id_number' => 'G78901234',
                'company' => 'Interswitch',
                'job_title' => 'Travel Coordinator',
                'vip_status' => 'silver',
                'total_stays' => 6,
                'total_nights' => 18,
                'total_spent' => 7500000,
                'currency_code' => 'NGN',
                'preferred_language' => 'en',
                'preferred_currency' => 'NGN',
                'dietary_restrictions' => json_encode([]),
                'special_notes' => json_encode(['Travel coordinator, books for executives']),
                'internal_notes' => 'Interswitch travel coordinator, potential referral source.',
            ],
            [
                'first_name' => 'Bola',
                'last_name' => 'Tinubu',
                'email' => 'bola.tinubu@email.com',
                'phone' => '+234-807-333-4444',
                'date_of_birth' => '1983-07-09',
                'nationality' => 'NG',
                'id_type' => 'drivers_license',
                'id_number' => 'LAG-7654321DD04',
                'company' => 'Julius Berger Nigeria',
                'job_title' => 'Project Manager',
                'vip_status' => 'none',
                'total_stays' => 4,
                'total_nights' => 12,
                'total_spent' => 5500000,
                'currency_code' => 'NGN',
                'preferred_language' => 'en',
                'preferred_currency' => 'NGN',
                'dietary_restrictions' => json_encode([]),
                'special_notes' => json_encode(['Extended stay for project']),
                'internal_notes' => 'Construction project nearby.',
            ],
            [
                'first_name' => 'Akinwale',
                'last_name' => 'Adeniyi',
                'email' => 'akinwale.adeniyi@email.com',
                'phone' => '+234-908-444-5555',
                'date_of_birth' => '1979-11-15',
                'nationality' => 'GB',
                'id_type' => 'international_passport',
                'id_number' => 'H89012345',
                'company' => 'Shell Nigeria',
                'job_title' => 'Senior Consultant',
                'vip_status' => 'gold',
                'total_stays' => 20,
                'total_nights' => 60,
                'total_spent' => 25000000,
                'currency_code' => 'NGN',
                'preferred_language' => 'en',
                'preferred_currency' => 'GBP',
                'dietary_restrictions' => json_encode(['lactose_intolerant']),
                'special_notes' => json_encode(['Lactose-free options required']),
                'internal_notes' => 'UK-based Shell consultant, frequent traveler.',
            ],
            [
                'first_name' => 'James',
                'last_name' => 'Whitfield',
                'email' => 'james.whitfield@email.com',
                'phone' => '+44-7700-900123',
                'date_of_birth' => '1986-03-22',
                'nationality' => 'GB',
                'id_type' => 'international_passport',
                'id_number' => 'I90123456',
                'company' => 'British High Commission',
                'job_title' => 'Trade Attaché',
                'vip_status' => 'silver',
                'total_stays' => 7,
                'total_nights' => 21,
                'total_spent' => 14000000,
                'currency_code' => 'NGN',
                'preferred_language' => 'en',
                'preferred_currency' => 'GBP',
                'dietary_restrictions' => json_encode([]),
                'special_notes' => json_encode(['Diplomatic guest, protocol observed']),
                'internal_notes' => 'British diplomatic guest, protocol important.',
            ],
        ];

        foreach ($guests as $guestData) {
            $guest = Guest::firstOrCreate(
                ['email' => $guestData['email']],
                $guestData
            );

            if ($guest->total_stays > 0 && is_null($guest->last_stayed_at)) {
                $guest->update(['last_stayed_at' => now()->subDays(rand(1, 30))]);
            }
        }
    }
}
